#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="Mydatabase")]
public partial class MyDBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public MyDBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public MyDBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MyDBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MyDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MyDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[Function(Name="dbo.st_checkAccountGroup")]
	public int st_checkAccountGroup([Parameter(DbType="NVarChar(50)")] string username, [Parameter(DbType="NVarChar(50)")] string passuser)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, passuser);
		return ((int)(result.ReturnValue));
	}
	
	[Function(Name="dbo.st_login")]
	public int st_login([Parameter(DbType="NVarChar(50)")] string username, [Parameter(DbType="NVarChar(50)")] string pass)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, pass);
		return ((int)(result.ReturnValue));
	}
	
	[Function(Name="dbo.st_getgiaovieninfo")]
	public ISingleResult<st_getgiaovieninfoResult> st_getgiaovieninfo([Parameter(DbType="Int")] System.Nullable<int> id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
		return ((ISingleResult<st_getgiaovieninfoResult>)(result.ReturnValue));
	}
	
	[Function(Name="dbo.st_getgiaovienid")]
	public int st_getgiaovienid([Parameter(DbType="NVarChar(50)")] string username)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username);
		return ((int)(result.ReturnValue));
	}
	
	[Function(Name="dbo.st_getsinhvienid")]
	public int st_getsinhvienid([Parameter(DbType="NVarChar(50)")] string username)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username);
		return ((int)(result.ReturnValue));
	}
	
	[Function(Name="dbo.st_changepasswordc1")]
	public int st_changepasswordc1([Parameter(DbType="NVarChar(50)")] string username, [Parameter(DbType="NVarChar(50)")] string passcu, [Parameter(DbType="NVarChar(50)")] string passmoi)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, passcu, passmoi);
		return ((int)(result.ReturnValue));
	}
	
	[Function(Name="dbo.st_getaccountinfo")]
	public ISingleResult<st_getaccountinfoResult> st_getaccountinfo([Parameter(DbType="Int")] System.Nullable<int> id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
		return ((ISingleResult<st_getaccountinfoResult>)(result.ReturnValue));
	}
	
	[Function(Name="dbo.st_changepasswordc2")]
	public int st_changepasswordc2([Parameter(DbType="NVarChar(50)")] string username, [Parameter(DbType="NVarChar(50)")] string passc2cu, [Parameter(DbType="NVarChar(50)")] string passc2moi)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, passc2cu, passc2moi);
		return ((int)(result.ReturnValue));
	}
	
	[Function(Name="dbo.st_forgotpassword")]
	public int st_forgotpassword([Parameter(DbType="NVarChar(50)")] string username, [Parameter(DbType="NVarChar(50)")] string passc2, [Parameter(DbType="NVarChar(50)")] string passmoi)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, passc2, passmoi);
		return ((int)(result.ReturnValue));
	}
	
	[Function(Name="dbo.st_getpointofstudent")]
	public ISingleResult<st_getpointofstudentResult> st_getpointofstudent([Parameter(DbType="Char(5)")] string hocky, [Parameter(DbType="Int")] System.Nullable<int> id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hocky, id);
		return ((ISingleResult<st_getpointofstudentResult>)(result.ReturnValue));
	}
	
	[Function(Name="dbo.st_getsinhvieninfo")]
	public ISingleResult<st_getsinhvieninfoResult> st_getsinhvieninfo([Parameter(DbType="Int")] System.Nullable<int> id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
		return ((ISingleResult<st_getsinhvieninfoResult>)(result.ReturnValue));
	}
}

public partial class st_getgiaovieninfoResult
{
	
	private int _id;
	
	private string _magv;
	
	private string _tengv;
	
	private string _gioitinh;
	
	private System.Nullable<System.DateTime> _ngaysinh;
	
	private string _diachi;
	
	private string _quequan;
	
	private string _sdt;
	
	private string _capbac;
	
	private string _email;
	
	private System.Nullable<System.DateTime> _ngayvaolam;
	
	public st_getgiaovieninfoResult()
	{
	}
	
	[Column(Storage="_id", DbType="Int NOT NULL")]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[Column(Storage="_magv", DbType="Char(10) NOT NULL", CanBeNull=false)]
	public string magv
	{
		get
		{
			return this._magv;
		}
		set
		{
			if ((this._magv != value))
			{
				this._magv = value;
			}
		}
	}
	
	[Column(Storage="_tengv", DbType="NVarChar(50)")]
	public string tengv
	{
		get
		{
			return this._tengv;
		}
		set
		{
			if ((this._tengv != value))
			{
				this._tengv = value;
			}
		}
	}
	
	[Column(Storage="_gioitinh", DbType="NVarChar(10)")]
	public string gioitinh
	{
		get
		{
			return this._gioitinh;
		}
		set
		{
			if ((this._gioitinh != value))
			{
				this._gioitinh = value;
			}
		}
	}
	
	[Column(Storage="_ngaysinh", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> ngaysinh
	{
		get
		{
			return this._ngaysinh;
		}
		set
		{
			if ((this._ngaysinh != value))
			{
				this._ngaysinh = value;
			}
		}
	}
	
	[Column(Storage="_diachi", DbType="NVarChar(50)")]
	public string diachi
	{
		get
		{
			return this._diachi;
		}
		set
		{
			if ((this._diachi != value))
			{
				this._diachi = value;
			}
		}
	}
	
	[Column(Storage="_quequan", DbType="NVarChar(50)")]
	public string quequan
	{
		get
		{
			return this._quequan;
		}
		set
		{
			if ((this._quequan != value))
			{
				this._quequan = value;
			}
		}
	}
	
	[Column(Storage="_sdt", DbType="NVarChar(30)")]
	public string sdt
	{
		get
		{
			return this._sdt;
		}
		set
		{
			if ((this._sdt != value))
			{
				this._sdt = value;
			}
		}
	}
	
	[Column(Storage="_capbac", DbType="NVarChar(30)")]
	public string capbac
	{
		get
		{
			return this._capbac;
		}
		set
		{
			if ((this._capbac != value))
			{
				this._capbac = value;
			}
		}
	}
	
	[Column(Storage="_email", DbType="NVarChar(40)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this._email = value;
			}
		}
	}
	
	[Column(Storage="_ngayvaolam", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> ngayvaolam
	{
		get
		{
			return this._ngayvaolam;
		}
		set
		{
			if ((this._ngayvaolam != value))
			{
				this._ngayvaolam = value;
			}
		}
	}
}

public partial class st_getaccountinfoResult
{
	
	private int _id;
	
	private string _matv;
	
	private string _password1;
	
	private string _password2;
	
	private string _nhom;
	
	public st_getaccountinfoResult()
	{
	}
	
	[Column(Storage="_id", DbType="Int NOT NULL")]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[Column(Storage="_matv", DbType="Char(10) NOT NULL", CanBeNull=false)]
	public string matv
	{
		get
		{
			return this._matv;
		}
		set
		{
			if ((this._matv != value))
			{
				this._matv = value;
			}
		}
	}
	
	[Column(Storage="_password1", DbType="NVarChar(50)")]
	public string password1
	{
		get
		{
			return this._password1;
		}
		set
		{
			if ((this._password1 != value))
			{
				this._password1 = value;
			}
		}
	}
	
	[Column(Storage="_password2", DbType="NVarChar(50)")]
	public string password2
	{
		get
		{
			return this._password2;
		}
		set
		{
			if ((this._password2 != value))
			{
				this._password2 = value;
			}
		}
	}
	
	[Column(Storage="_nhom", DbType="NVarChar(20)")]
	public string nhom
	{
		get
		{
			return this._nhom;
		}
		set
		{
			if ((this._nhom != value))
			{
				this._nhom = value;
			}
		}
	}
}

public partial class st_getpointofstudentResult
{
	
	private string _tenmon;
	
	private System.Nullable<int> _diemhs1;
	
	private System.Nullable<int> _diemhs2;
	
	private System.Nullable<int> _diemhs3;
	
	private System.Nullable<double> _diemtb;
	
	public st_getpointofstudentResult()
	{
	}
	
	[Column(Storage="_tenmon", DbType="NVarChar(30)")]
	public string tenmon
	{
		get
		{
			return this._tenmon;
		}
		set
		{
			if ((this._tenmon != value))
			{
				this._tenmon = value;
			}
		}
	}
	
	[Column(Storage="_diemhs1", DbType="Int")]
	public System.Nullable<int> diemhs1
	{
		get
		{
			return this._diemhs1;
		}
		set
		{
			if ((this._diemhs1 != value))
			{
				this._diemhs1 = value;
			}
		}
	}
	
	[Column(Storage="_diemhs2", DbType="Int")]
	public System.Nullable<int> diemhs2
	{
		get
		{
			return this._diemhs2;
		}
		set
		{
			if ((this._diemhs2 != value))
			{
				this._diemhs2 = value;
			}
		}
	}
	
	[Column(Storage="_diemhs3", DbType="Int")]
	public System.Nullable<int> diemhs3
	{
		get
		{
			return this._diemhs3;
		}
		set
		{
			if ((this._diemhs3 != value))
			{
				this._diemhs3 = value;
			}
		}
	}
	
	[Column(Storage="_diemtb", DbType="Float")]
	public System.Nullable<double> diemtb
	{
		get
		{
			return this._diemtb;
		}
		set
		{
			if ((this._diemtb != value))
			{
				this._diemtb = value;
			}
		}
	}
}

public partial class st_getsinhvieninfoResult
{
	
	private int _id;
	
	private string _masv;
	
	private string _hoten;
	
	private string _gioitinh;
	
	private System.Nullable<System.DateTime> _ngaysinh;
	
	private string _malop;
	
	private string _diachi;
	
	private string _quequan;
	
	private string _sdt;
	
	private string _bachoc;
	
	private string _nienkhoa;
	
	public st_getsinhvieninfoResult()
	{
	}
	
	[Column(Storage="_id", DbType="Int NOT NULL")]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[Column(Storage="_masv", DbType="Char(10) NOT NULL", CanBeNull=false)]
	public string masv
	{
		get
		{
			return this._masv;
		}
		set
		{
			if ((this._masv != value))
			{
				this._masv = value;
			}
		}
	}
	
	[Column(Storage="_hoten", DbType="NVarChar(50)")]
	public string hoten
	{
		get
		{
			return this._hoten;
		}
		set
		{
			if ((this._hoten != value))
			{
				this._hoten = value;
			}
		}
	}
	
	[Column(Storage="_gioitinh", DbType="NVarChar(10)")]
	public string gioitinh
	{
		get
		{
			return this._gioitinh;
		}
		set
		{
			if ((this._gioitinh != value))
			{
				this._gioitinh = value;
			}
		}
	}
	
	[Column(Storage="_ngaysinh", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> ngaysinh
	{
		get
		{
			return this._ngaysinh;
		}
		set
		{
			if ((this._ngaysinh != value))
			{
				this._ngaysinh = value;
			}
		}
	}
	
	[Column(Storage="_malop", DbType="NChar(10)")]
	public string malop
	{
		get
		{
			return this._malop;
		}
		set
		{
			if ((this._malop != value))
			{
				this._malop = value;
			}
		}
	}
	
	[Column(Storage="_diachi", DbType="NVarChar(50)")]
	public string diachi
	{
		get
		{
			return this._diachi;
		}
		set
		{
			if ((this._diachi != value))
			{
				this._diachi = value;
			}
		}
	}
	
	[Column(Storage="_quequan", DbType="NVarChar(50)")]
	public string quequan
	{
		get
		{
			return this._quequan;
		}
		set
		{
			if ((this._quequan != value))
			{
				this._quequan = value;
			}
		}
	}
	
	[Column(Storage="_sdt", DbType="NVarChar(30)")]
	public string sdt
	{
		get
		{
			return this._sdt;
		}
		set
		{
			if ((this._sdt != value))
			{
				this._sdt = value;
			}
		}
	}
	
	[Column(Storage="_bachoc", DbType="NVarChar(30)")]
	public string bachoc
	{
		get
		{
			return this._bachoc;
		}
		set
		{
			if ((this._bachoc != value))
			{
				this._bachoc = value;
			}
		}
	}
	
	[Column(Storage="_nienkhoa", DbType="NVarChar(50)")]
	public string nienkhoa
	{
		get
		{
			return this._nienkhoa;
		}
		set
		{
			if ((this._nienkhoa != value))
			{
				this._nienkhoa = value;
			}
		}
	}
}
#pragma warning restore 1591
